<a href="https://colab.research.google.com/github/aveshag/SHALA2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [5]:
import numpy as np

a = np.random.random_sample((3,5))
b = np.random.random_sample((3,5))

print(a)
print(b)

[[0.53992041 0.93630869 0.94701675 0.15804189 0.08853814]
 [0.67578647 0.13924711 0.72374652 0.06372963 0.33783684]
 [0.12340917 0.40341997 0.36232962 0.1373268  0.47686389]]
[[0.67872949 0.50567145 0.48970551 0.45215845 0.35995104]
 [0.35831238 0.97212063 0.09817458 0.09302152 0.23471187]
 [0.86523625 0.06861    0.40936558 0.46515291 0.48804225]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [19]:
c = np.arange(100).reshape(1,100)
print(c)

d = np.zeros((3,3), dtype = float)
print(d)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
  72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
  96 97 98 99]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [25]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print(e)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [28]:
f = np.ones((5,5))
print(f)
g = np.eye(5)
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [37]:
h = c.reshape(10,10)
print(h)

c_dash = h.flatten()
print(c_dash)

if c.shape == c_dash.shape:
  print ("YES")
else:
  print ("NO")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
NO


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [41]:
A = np.random.rand(2,10,5)

A_dash = np.transpose(A,(2,0,1))
print(A_dash)



[[[0.77708314 0.21312004 0.97137634 0.69516801 0.05976058 0.63884202
   0.62873703 0.31508765 0.43840269 0.56851136]
  [0.44071288 0.10862246 0.96493891 0.53223525 0.26941391 0.09309476
   0.20681131 0.2021624  0.14936049 0.527376  ]]

 [[0.49299304 0.36809731 0.50313926 0.53390011 0.05783417 0.51601854
   0.40981725 0.72056518 0.46897285 0.98752777]
  [0.20798465 0.4670789  0.87312219 0.84668585 0.09197622 0.32247217
   0.86857016 0.82031087 0.6436083  0.33153036]]

 [[0.30174186 0.52704328 0.98715165 0.12541487 0.35337878 0.9206983
   0.30864379 0.01013314 0.87196474 0.08318531]
  [0.65756904 0.28180953 0.05305869 0.12920445 0.1578606  0.7211676
   0.59251981 0.15806883 0.75686141 0.02409134]]

 [[0.10847216 0.25375315 0.30249068 0.55295772 0.79162607 0.62954783
   0.41412592 0.83592083 0.2625121  0.92629891]
  [0.69074851 0.84297421 0.02502772 0.78672793 0.57148374 0.81409277
   0.87274719 0.09365001 0.36026908 0.56877861]]

 [[0.18884436 0.98809285 0.20863634 0.30785956 0.73862309 

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [47]:
np.random.seed(0)
X = np.random.rand(10,5)

print("max for each column = {}".format(np.max(X, axis = 0)))
print("index of max value for each column = {}\n".format(np.argmax(X, axis = 0)))

print("max for each row = {}".format(np.max(X, axis = 1)))
print("index of max value for each row = {}\n".format(np.argmax(X, axis = 1)))

print("max = {}".format(np.max(X)))
print("index = {}".format(np.argmax(X)))



max for each column = [0.97861834 0.79915856 0.94466892 0.96366276 0.87001215]
index of max value for each column = [4 4 5 1 3]

max for each row = [0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787]
index of max value for each row = [1 3 3 4 0 2 1 3 2 0]

max = 0.978618342232764
index = 20


Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [49]:
print("mean of each column = {}".format(np.mean(X, axis = 0)))
print("standard deviation of each column = {}\n".format(np.std(X, axis = 0)))

print("mean of each row = {}".format(np.mean(X, axis = 1)))
print("standard deviation of each row = {}\n".format(np.std(X, axis = 1)))

print("mean = {}".format(np.mean(X)))
print("standard deviation = {}".format(np.std(X)))

mean of each column = [0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
standard deviation of each column = [0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]

mean of each row = [0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
standard deviation of each row = [0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332]

mean = 0.5379651182755409
standard deviation = 0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [66]:
np.random.seed(3)
Y = np.random.rand(10,10)

det = np.linalg.det(Y)
rank = np.linalg.matrix_rank(Y)
diagonal = np.diag(Y)
trace = np.trace(Y)
eigval, eigvect = np.linalg.eig(Y)
u,singval,vt = np.linalg.svd(Y)
inv = np.linalg.pinv(Y)
mat_mul = np.matmul(Y, X)
ele_mul = Y * inv

print("Determinant = {}\n".format(det))
print("Rank of the matrix = {}\n".format(rank))
print("Diagonal Elements = {}\n".format(diagonal))
print("Trace = {}\n".format(trace))
print("Eigen values = {}\n".format(eigval))
print("Singular Value Decomposition")
print("U = {}\n".format(u))
print("Singular Values = {}\n".format(singval))
print("Transpose(V) = {}\n".format(vt))
print("Inverse = {}\n".format(inv))
print("Matrix Multiplication = {}\n".format(mat_mul))
print("Element-wise multiplication = {}\n".format(ele_mul))

Determinant = -0.012807808169095483

Rank of the matrix = 10

Diagonal Elements = [0.5507979  0.45683322 0.44045372 0.84575087 0.4576864  0.36217621
 0.06152893 0.19897603 0.92672568 0.19638058]

Trace = 4.497309545724899

Eigen values = [ 4.797525  +0.j          0.72411408+0.52238181j  0.72411408-0.52238181j
 -0.48250062+0.55413671j -0.48250062-0.55413671j -0.6909002 +0.j
 -0.25905659+0.32357377j -0.25905659-0.32357377j  0.2127855 +0.08352477j
  0.2127855 -0.08352477j]

Singular Value Decomposition
U = [[-0.31776408 -0.02455508 -0.60644878 -0.17883359 -0.12672161  0.14873878
  -0.17823942 -0.52859453 -0.02295855 -0.38570883]
 [-0.26118514 -0.10864541 -0.24911354  0.26547359  0.52168399 -0.25773901
  -0.46995326  0.21752636 -0.39285046  0.16234491]
 [-0.31347907 -0.34483471 -0.25292297  0.1214296   0.1486964   0.33436315
   0.54080229  0.48017168  0.05660692 -0.20966421]
 [-0.35815379  0.59490017  0.30255161  0.15850614 -0.11046295  0.3051409
   0.07395537  0.03044889 -0.50561658 -0.18

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"



### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.